language: node_js
node_js:
-  6
before_install:
- echo "//registry.npmjs.org/:_authToken=\${NPMAUTH}" > .npmrc
- echo "//registry.npmjs.org/:_password=\${NPMTOKEN}" >> .npmrc
- echo "//registry.npmjs.org/:username=lccgov" >> .npmrc
- echo "//registry.npmjs.org/:email=developer@leeds.gov.uk" >> .npmrc
install:
- npm install -g npm
- npm install gulp gulp-cli
- npm install
script:
- npm whoami
- chmod +x ./bin/publish.sh
- "./bin/publish.sh"
env:
  global:
  - secure: YE52aBpTMYaqvCI0m2NSu6ygOFPMij+383Wq04D/V0HUVMQvWxLHiU5+5h0Nb72IKt87Lk1PV+ivpIgBVu0WC/OkyScoZmiIQ9jXbLoa4rh+VAxJVqZpaf3x7X/IzEwj/pJwEhkwuNa5AU7Tzi8mISwGD5uXG3bFfdYurXaOhVNEFgFNbJO5EeaK6SOWXdXYhtq6niAvgotVHPoUfUmKTjCYaZ3QVomdOPbluHarJ9kAVOCLztZJjSgjuuz3tVhzuzCDFWCDJtYpxu80gjh5R0Snb1R4nn3MUYUQJ85YDjmiliwDKH3kHw3qcYwFFzXw/QBZj2dENPbEOBpTD7jXbYO/AgU295dLpXNez7A0Fnq19nh58EZbDRmfJ4+FrlmIbx0pKJpZmqunij7TrtCsakTuHYOln++kY7sJwKs1LvN+s+BHcU3QrZzu7SZGykzU2eu0e6q9TCxcSvUBxxX88oCrLFph8H0BSDXl817hpxURff47E3xaqQuP0WeyqCLybOPWMvGYBUQP67Aj5Mg4v3wQQaKLL70rv5imFaIdU+AbVIzzQltW4CtD786lUtfdB7dz+WCFKlUEyMdKuZuQkCYI0Z8Y7yHt4QuyUFcUzmZBzm4Ax+xhyKEBMu06LSLAENkS7oqL6e2qd1vUceydM6pRs1O8slcrTDBeAKJstOs=
  - secure: AubPsK6eWkwTSC/C43xBh8IoKSFKhMY16UuKZPBB94BgUVoc15lMgVLjjlrPBruFKG8pat+YA86HN3/6Wfh772vhXoh3OP9bcfXcvXnFvq+jkr24g1PLuU72VbxpV/1kX09+gf+7Sk0p2SrPY/Aq3/QPXFs3m1GSajqyMw32TgW+eJ1iSbZ13cj7ZSm7cMO4VGfMZvayrWcug9fgg741F6Z1iEfYu/uCBaydV/+i/yG5+4lmXGGRTKpcaEL1OV8Qld2Vd7ndMpVYwcbKgfGYYTpWdhknslGulMvMte15JxO+b0BJyZ4wv1knRGNd/cOb/BWzxY9roHcfYUrbXU1pwxAZmjDtYl9p/nKcTBEHNoZ0PvThX+RjDF3VVVmVfwgo5MqmQoDtdIP8gMhFuecItJv5B2oYRMrAUGrvAmbB4OLRbMpXc68Q0DJIqiasqIZtrQEt65HxjDkb0dNue0TzE4hKPcQ/D3AFaKLUNAOjY6PyaevAUhoU2/9uS5TBPHdoBWQeFy5T5XECVhZgXv3ooshW07D8GSsomQXRxDapBJ8d22LhI5cOeikHWo2oXH9v3IvcTmid7YUZKJ+K6Fez+boSBc7cbFJa3wr3pWwlvgVy5SveJojzEEMASsNXSnlf1LO4f7x4DzWOwd3K3y1N8+oDFTDUt+8ek23U/ovNXOE=